# Generated by Django 4.1 on 2022-08-28 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tinda", "0004_comment_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadmodel",
            name="owner",
        ),
    ]
