# Generated by Django 4.1 on 2022-08-28 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tinda", "0005_remove_uploadmodel_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tindadates",
            old_name="username",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="uploadmodel",
            name="likes",
        ),
        migrations.AddField(
            model_name="uploadmodel",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
